SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM 
(
    SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) RI 
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) RR
ON RI.REST_ID = RR.REST_ID
Order BY SCORE DESC, FAVORITES DESC