SELECT t1.FOOD_TYPE, t1.REST_ID, t1.REST_NAME, t2.FAVORITES
FROM REST_INFO t1
JOIN
(
SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES FROM REST_INFO
GROUP BY FOOD_TYPE
) t2
ON t1.FOOD_TYPE = t2.FOOD_TYPE and t1.FAVORITES = t2.FAVORITES
ORDER BY FOOD_TYPE DESC;

