SELECT t1.FOOD_TYPE, t1.REST_ID, t1.REST_NAME, t2.FAVORITES
FROM REST_INFO t1
JOIN
(
SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES FROM REST_INFO
GROUP BY FOOD_TYPE
) t2
ON t1.FOOD_TYPE = t2.FOOD_TYPE and t1.FAVORITES = t2.FAVORITES
ORDER BY FOOD_TYPE DESC;

--- 

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO ri1
WHERE FAVORITES = (
	SELECT MAX(FAVORITES)
	FROM REST_INFO ri2
	WHERE ri1.FOOD_TYPE = ri2.FOOD_TYPE
)
ORDER BY
	FOOD_TYPE DESC;